---
- include_tasks: 'family-debian.yml'
  when: |
    ansible_os_family == 'Debian'

- include_tasks: 'family-redhat.yml'
  when: |
    ansible_os_family == 'RedHat'

- include_tasks: 'system-openbsd.yml'
  when: |
    ansible_system == 'OpenBSD'
