namespace: 'msamsonoff'
name: 'core'
version: '0.1.0'
readme: 'README.md'
authors:
- Matthew W. Samsonoff <matt.samsonoff@gmail.com>
description: 'Core Ansible Collection'
license:
- 'MIT'
license_file: 'LICENSE'
tags:
dependencies:
repository: 'https://github.com/msamsonoff/ansible-core'
documentation: 'https://github.com/msamsonoff/ansible-core/blob/master/README.md'
homepage: 'https://github.com/msamsonoff/ansible-core'
issues: 'https://github.com/msamsonoff/ansible-core/issues'
